### ISSUE TITLE
libApexFramework

### ISSUE THREAD

**Issue by Fivetuple** [phuselab/openFACS#1]
Hi,

I have had the following error on two machines,

~$ ./ActionUnitsFace-Linux-Shipping
./ActionUnitsFace-Linux-Shipping: error while loading shared libraries: libApexFramework.so: cannot open shared object file: No such file or directory

Could you advise?

**Comment by vcuculo** [comment]
Thank you very much for your issue. That error concerns with a missing third-party dependency that handles the physics of the avatar. I'll figure out if it is essential for the execution of the project, otherwise I'll recompile it by removing it. I will let you know as soon as possible.

**Comment by vcuculo** [comment]
Please refer to the new release v1.0.1

**Comment by mkchoithani** [comment]
HI There, 

I am trying to run your project and I am trying it on Rocky linux and I am getting below error
Can you help? Why did you create the core code in C++ ? If the scripts were in python the core part could have been written in python as well? Also , why did you use the UDP to send info to the core code. Ideally a rest end point would have been a better approach.  Can you please help me to compile the code? I am trying to understand how can we change the face expression on existing 3d character? 
FACS recognition is present in pyfeet and opencv and it works fine. I was checking implementation of the same on existing character. 

manish@localhost facstest]$ ls -lrt
total 330900
-rw-r--r--. 1 manish manish 338841246 Dec  6  2021 openFACS_Linux.tar.gz
drwxr-xr-x. 4 manish manish       107 Oct 28 16:00 LinuxNoEditor
[manish@localhost facstest]$ cd LinuxNoEditor/
[manish@localhost LinuxNoEditor]$ ls -rlt
total 8
-rwxr-xr-x. 1 manish manish 311 Sep 18  2019 ActionUnitsFace.sh
-rw-r--r--. 1 manish manish 893 Sep 18  2019 Manifest_NonUFSFiles_Linux.txt
drwxr-xr-x. 3 manish manish  22 Sep 18  2019 Engine
drwxr-xr-x. 4 manish manish  37 Sep 18  2019 ActionUnitsFace
[manish@localhost LinuxNoEditor]$ ./ActionUnitsFace.sh 
4.19.2-0+++UE4+Release-4.19 516 0
Disabling core dumps.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
[manish@localhost LinuxNoEditor]$ cd ..
[manish@localhost facstest]$ ls -lrt
total 330900
-rw-r--r--. 1 manish manish 338841246 Dec  6  2021 openFACS_Linux.tar.gz
drwxr-xr-x. 4 manish manish       107 Oct 28 16:00 LinuxNoEditor
[manish@localhost facstest]$ 
[manish@localhost facstest]$

**Comment by mkchoithani** [comment]
I checked the python script as well, it renders the UI but the server part I can't yet and trying to run it . I need to see how can we make the changes in the 3d character at run time.

**Comment by mkchoithani** [comment]
Another thing, I tried running it on Mac and the script do not work on Mac. I guess you should mention the linux variant you think the code will work .
